name: Build and Release Pathfinder

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ] # vX.Y.Z
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build (${{ matrix.os }} with Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
      - name: Pull
        uses: actions/checkout@v4

      - name: Set python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: CMake
        shell: bash
        run: |
          cd src/PATHFINDER
          
          cmake -S . -B temp_cmake_build -DCMAKE_BUILD_TYPE=Release
          cmake --build temp_cmake_build --config Release
          
          rm -rf temp_cmake_build
          
          if [ -d "build/Release" ]; then
              mv build/Release/* build/
              rm -rf build/Release
          fi

      - name: Install Tkinter Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y python3-tk

      - name: Get python deps
        run: |
          python -m pip install --target=src/libdeps pygame customtkinter CTkListbox matplotlib

      - name: Zip project
        shell: bash
        run: |
          7z a -tzip "${{ matrix.os }}-python${{ matrix.python-version }}.zip" . -xr!".git*"

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: release-zip-${{ matrix.os }}-${{ matrix.python-version }}
          path: ${{ matrix.os }}-python${{ matrix.python-version }}.zip
          retention-days: 1

  release:
    name: Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Get zips
        uses: actions/download-artifact@v4
        with:
          path: all-artifacts

      - name: Group artifacts
        run: |
          mkdir release_assets
          find all-artifacts -name "*.zip" -exec mv {} release_assets/ \;

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: release_assets/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}